export enum NonWorkingDaysError {
  ERROR_GETTING_NON_WORKING_DAYS_OF_YEAR = 'ERROR_GETTING_NON_WORKING_DAYS_OF_YEAR',
  ERROR_GETTING_NON_WORKING_DAYS_OF_MONTH = 'ERROR_GETTING_NON_WORKING_DAYS_OF_MONTH',
  ERROR_COUNTING_NON_WORKING_DAYS_OF_MONTH = 'ERROR_COUNTING_NON_WORKING_DAYS_OF_MONTH',
  INVALID_YEAR = 'INVALID_YEAR',
  INVALID_MONTH = 'INVALID_MONTH',
}
